/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u2a5hurricane;

/**
 *
 * @author Corbin
 */
public class U2A5Hurricane extends javax.swing.JFrame {

    /**
     * Creates new form U2A5Hurricane
     */
    public U2A5Hurricane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        catergoryLabel = new javax.swing.JLabel();
        buttonInput = new javax.swing.JButton();
        imputField = new javax.swing.JTextField();
        outputLabel1 = new javax.swing.JLabel();
        outputLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hurricane Scale");

        catergoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catergoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        catergoryLabel.setText("Please enter hurricane category (1-5):");

        buttonInput.setText("Select");
        buttonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInputActionPerformed(evt);
            }
        });

        imputField.setText(" ");
        imputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imputFieldActionPerformed(evt);
            }
        });

        outputLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outputLabel1.setForeground(new java.awt.Color(255, 255, 255));
        outputLabel1.setText(" ");

        outputLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outputLabel2.setForeground(new java.awt.Color(255, 255, 255));
        outputLabel2.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(catergoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imputField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outputLabel2)
                                    .addComponent(outputLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catergoryLabel)
                    .addComponent(buttonInput)
                    .addComponent(imputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(outputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputLabel2)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imputFieldActionPerformed


    }//GEN-LAST:event_imputFieldActionPerformed

    private void buttonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInputActionPerformed
        
        int hurricane = 0;

switch (hurricane)

{  
    case 1: 
        outputLabel1.setText("Windspeed for Category 1 are:");
        outputLabel2.setText("74-95 mph or 64-82 kt or 119-153 km/hr"); 
        break; 
    case 2: 
        outputLabel1.setText("Windspeed for Category 2 are:");
        outputLabel2.setText("74-95 mph or 64-82 kt or 119-153 km/hr"); 
    break;
    case 3:
        outputLabel1.setText("Windspeed for Category 3 are:");
        outputLabel2.setText("74-95 mph or 64-82 kt or 119-153 km/hr"); 
    break;
    case 4:
        outputLabel1.setText("Windspeed for Category 4 are:");
        outputLabel2.setText("74-95 mph or 64-82 kt or 119-153 km/hr"); 
    break;
    case 5:
        outputLabel1.setText("Windspeed for Category 5 are:");
        outputLabel2.setText("74-95 mph or 64-82 kt or 119-153 km/hr"); 
    break;
    default: 
        outputLabel1.setText("Please Enter a Number");
        outputLabel2.setText(" ");
}
    }//GEN-LAST:event_buttonInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U2A5Hurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U2A5Hurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U2A5Hurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U2A5Hurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U2A5Hurricane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInput;
    private javax.swing.JLabel catergoryLabel;
    private javax.swing.JTextField imputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel outputLabel1;
    private javax.swing.JLabel outputLabel2;
    // End of variables declaration//GEN-END:variables
}
